### ISSUE TITLE
Properties should have same names as in CSS spec

### ISSUE THREAD

**Issue by AriaFallah** [alexfedoseev/bs-emotion#13]
e.g. `alignFlexItems` should just be `alignItems` (same goes for the other different ones). With your version there's an increase in clarity, but I don't think that's worth the churn of every user having to learn this library's specific flavor of CSS.

Otherwise, this library is amazing.

**Comment by alexfedoseev** [comment]
@AriaFallah The problem w/ `alignItems` as well as with `justifyContent` etc is that it's not possible (or  I don't know how) to have single function for both—flex and grid—since arguments have different types (`flex-start` vs `start`, `flex-end` vs `end`). It's possible to squash them (`flex-start` w/ `start` etc) into single type tho but it's kinda meh imo.

But I'm definitely open for suggestions and if most of the users think that spec compliance (in terms of naming) is more important than type correctness this can be reconsidered.

**Comment by alexfedoseev** [comment]
Ok, convinced :) I'll update these parts.

**Comment by AriaFallah** [comment]
Thanks for being so receptive to the feedback :)
